### ISSUE TITLE
Migrate wiki setup info to README.md

### ISSUE THREAD

**Issue by bmenn** [anidata/ht-archive#14]
Copy the useful bits of setup information on the wiki page to README.md so setup instructions have more visibility.

**Comment by Engineiro** [comment]
During the anidata meetup 4/18/17 some of us in the room were walking through the install instructions, so I think we need to bring that feedback in (if changes were discovered) first before closing this issue.

**Comment by bmenn** [comment]
@danlrobertson 

Per @Engineiro's comments above, did you have feedback from helping others get set up? My feedback is that #13 might need to be addressed sooner rather than later.

**Comment by Engineiro** [comment]
sorry this was buried in my email. Yes, received feedback and took it in. I finished set up myself too and the rest looked complete.

**Comment by bmenn** [comment]
@Engineiro thanks for the feedback.

@blakeflei You mentioned you tried the setup instructions recent. Any feedback?

**Comment by blakeflei** [comment]
@bmenn Put together some updated instructions into a pull request - definitely open to feedback!

**Comment by bmenn** [comment]
Closing after merging #18
