### ISSUE TITLE
Role dbadmin doesn't exist by default on Postgres server

### ISSUE THREAD

**Issue by coxjonc** [anidata/ht-archive#6]
Just a quick note about a lack of clarity in the docs: If a user installs and starts a postgres server themselves instead of using the Docker command that creates a user named `dbadmin`, then running the queries in [the Wiki](https://github.com/anidata/ht-archive/wiki#setting-up-the-database) to create and populate the crawler DB as user `dbadmin` will result in a "role does not exist" error. If they try to execute the commands as user `postgres`, loading data from the SQL dump into the database throws errors, since `crawler.sql` specifies that the commands should be executed by a user named `dbadmin`. We should specify in the Wiki that users who don't use Docker will have to create a superuser named `dbadmin` for the commands in the wiki to work.

On a related note, to run the commands to create the database from the command line you have to run the commands as user `postgres` like so `$ sudo -u postgres psql -c "CREATE DATABASE foo;"`. Trying to run the commands as they appear in the wiki `psql --username postgres -c "CREATE DATABASE foo"` fails because of a peer authentication error. See [this SO answer](http://stackoverflow.com/a/17443990/4599578) for an explanation of why.

**Comment by dlrobertson** [comment]
These should definitely be noted in the Wiki. Good Catch.

**Comment by coxjonc** [comment]
Updated wiki
